name: hello-world
replicas: 1

image: ${artifact.metadata.image}
dockercfg: ${artifact.source.dockerconfig}

createImagePullSecret: false

createNamespace: true
namespace: ${infra.kubernetes.namespace}

# Service Type allow you to specify what kind of service you want.
# Possible values for ServiceType are:
# ClusterIP | NodePort | LoadBalancer | ExternalName
serviceType: NodePort

# A Service can map an incoming port to any targetPort.
# targetPort is where application is listening on inside the container.
nameServicePort: http
servicePort: 8000
serviceTargetPort: 8000
serviceNodePort: 30888
namePromPort: prom
promServicePort: 8088
promeTargetPort: 8088

# Specify all environment variables to be added to the container.
# The following two maps, config and secrets, are put into a ConfigMap
# and a Secret, respectively.
# Both are added to the container environment in podSpec as envFrom source.
env:
  config:
    key1: value1
  secrets:
    key2: value2

# Prometheus Memory Query: jvm_memory_bytes_used{area="heap",pod_name="$hostName"} / 1024 / 1024
# Prometheus Buffer Query: jvm_buffer_pool_used_bytes{pool="direct",pod_name="$hostName"} / 1024 / 1024