apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  labels:
      app.kubernetes.io/name: {{.Values.name}}
      app.kubernetes.io/part-of: {{.Values.name}}
      app: {{.Values.name}}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /
    prometheus.io/port: "8088"
spec:
  type: {{.Values.serviceType}}
  ports:
  - name: {{.Values.nameServicePort}}
    port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    nodePort: {{.Values.serviceNodePort}}
    protocol: TCP
  - name: {{.Values.namePromPort}}
    port: {{.Values.promServicePort}}
    targetPort: {{.Values.promeTargetPort}}
    protocol: TCP
  selector:
    app: {{.Values.name}}